let form;
let amount;
let result;
let loremParagraphs = [`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eget dolor odio. Suspendisse quis nisl vel orci convallis eleifend. Ut fringilla lobortis arcu non volutpat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas vel sodales ligula. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis feugiat aliquet fringilla. Integer posuere purus sit amet enim lacinia, vel feugiat lectus scelerisque. Vivamus nibh augue, tristique sit amet augue in, finibus dapibus lectus.`,
`Praesent nibh lectus, aliquam vel rhoncus id, aliquet eget mi. Morbi molestie, elit eget venenatis molestie, justo urna vulputate velit, eu pharetra felis tortor eget tellus. Cras mattis tellus eu felis ornare interdum. Etiam diam leo, porta a mattis vitae, porttitor ac ex. Vivamus at nibh vel justo egestas congue condimentum id erat. Vivamus eget commodo nisl, nec dignissim lorem. Morbi scelerisque iaculis efficitur. Vestibulum maximus a quam id mollis. Ut egestas accumsan vulputate. Donec lobortis massa sit amet erat malesuada vehicula. Phasellus non nisl dolor. Vivamus semper, urna vitae blandit imperdiet, magna erat facilisis libero, et fermentum augue risus id sapien. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.`, 
`Maecenas euismod dignissim est at malesuada. Aenean sollicitudin arcu orci. Proin consequat ac odio ac ullamcorper. Vivamus sed scelerisque nibh. Nullam sapien quam, blandit id lorem eget, auctor auctor ligula. Nam posuere ex erat, vel bibendum elit tempus ut. In venenatis diam est, et ultricies lectus feugiat eu. Sed vitae varius odio. Nunc a suscipit turpis. Donec at mauris finibus, sagittis nunc nec, condimentum lacus.`, 
`Quisque consequat porttitor justo, et molestie nibh vehicula tempus. Nulla vel ipsum egestas, tempus magna vitae, consectetur massa. Pellentesque vehicula diam dui, blandit tincidunt mauris vulputate non. Donec vehicula urna et vestibulum dapibus. Fusce nulla nisi, rutrum ac lectus ac, accumsan sagittis eros. Sed at enim vel metus sagittis tincidunt. Vivamus eleifend nisi velit, nec vestibulum diam lobortis id. Integer consectetur, elit fermentum lobortis tincidunt, ipsum sem venenatis tortor, non tincidunt augue ante id ante. Sed ac risus in massa suscipit placerat. Sed euismod mi vel purus porttitor, nec volutpat libero euismod. Curabitur tincidunt risus eget metus sodales, id porttitor ex commodo. Nulla sit amet lacinia ligula. In viverra augue ut orci bibendum, id consequat nunc auctor. Pellentesque consequat sem tellus. Morbi sed magna a urna faucibus gravida.`, 
`In hac habitasse platea dictumst. Cras semper cursus pulvinar. Vivamus luctus arcu eu nisi convallis, non imperdiet est posuere. Nullam tincidunt cursus urna, quis dapibus tellus ultrices in. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vitae neque at purus eleifend porttitor. Quisque mattis mauris turpis, sed rutrum ante condimentum eget. Morbi congue sed leo sed blandit. Ut quis erat condimentum, interdum enim eu, ornare lorem. Suspendisse purus erat, aliquam id leo a, consectetur aliquam augue. Suspendisse sit amet fringilla quam, vel aliquet sapien. In suscipit nisi eu dapibus viverra.`, 
`Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc aliquam, dui nec porta sollicitudin, nibh ante semper nulla, vel hendrerit justo nunc ac justo. Mauris maximus odio quis quam auctor luctus. Phasellus ornare elementum diam at placerat. Ut pharetra porta metus ut malesuada. Duis eu blandit velit. Quisque erat ipsum, fringilla et eros id, luctus semper quam. Nunc eros tellus, pulvinar facilisis gravida vel, maximus vitae odio. Nullam egestas leo non ipsum efficitur, sit amet porttitor lacus efficitur. Ut efficitur quis lacus a sodales. Etiam condimentum facilisis facilisis. Mauris facilisis pretium mauris, ac ullamcorper felis finibus sit amet. Morbi pulvinar, massa quis porttitor scelerisque, mi purus pulvinar ligula, non posuere nulla ex sed velit. Quisque nec lectus lobortis, varius felis eget, placerat nisi. Aliquam eget leo sed nisl suscipit iaculis.`, 
`Morbi sit amet semper arcu. Cras mi magna, hendrerit at magna sed, facilisis rutrum urna. In hac habitasse platea dictumst. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed sagittis nec ligula et sagittis. In hac habitasse platea dictumst.`, 
`Phasellus a porta purus. Vivamus ultricies, velit eget aliquet suscipit, leo felis ullamcorper massa, sit amet porttitor turpis odio quis dui. Integer porta lobortis quam eget tincidunt. Donec mattis arcu vel dapibus ultricies. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras accumsan blandit molestie. Sed vel commodo sapien, in ultricies elit. Mauris lorem sapien, placerat nec porta convallis, sollicitudin vel turpis. Sed tempus euismod tincidunt. Praesent fringilla erat eu ante ornare pulvinar. Maecenas ultricies, nunc sed iaculis porta, augue lectus maximus ligula, non rutrum leo odio in sem. Aliquam rutrum lacus vel urna sagittis, vitae aliquam quam interdum.`, 
`Nunc venenatis placerat efficitur. Etiam a faucibus urna. Nullam viverra libero a nunc elementum, eget lobortis metus vehicula. Mauris mollis porttitor sem non euismod. Phasellus aliquet non tellus a posuere. Cras malesuada erat at sodales mollis. Maecenas placerat ullamcorper pretium. Maecenas suscipit in urna et placerat.`, 
`Mauris laoreet erat enim, at facilisis ex tempus a. Proin id est eget sem sollicitudin congue. Aliquam nec luctus justo, at sagittis augue. Quisque bibendum ullamcorper ex, sit amet blandit quam consectetur ac. Nam tellus nunc, lacinia ac erat id, cursus commodo tortor. Praesent fringilla quis felis quis eleifend. Donec eget ex congue, interdum turpis faucibus, tempor velit. Ut vel fermentum metus, sit amet interdum lorem. Sed quam felis, aliquet ut fermentum et, placerat accumsan nisl. Cras nec ornare urna, at molestie dolor. Integer pharetra consectetur risus sit amet tempor. Sed non purus et dolor elementum tristique eget eget enim. Sed sagittis libero fermentum, pellentesque eros quis, varius arcu. Nullam sem justo, ornare vel condimentum ut, blandit sed dui. Aenean ipsum mi, posuere eget erat sit amet, pretium dictum urna. Nulla facilisi.`,
`Nulla luctus libero a rhoncus molestie. Fusce ultricies ultrices feugiat. Phasellus aliquam lacus nulla, ac mollis nunc eleifend suscipit. Nullam enim tortor, dignissim vel ornare vitae, venenatis vel erat. Vivamus eleifend molestie massa quis gravida. Quisque rhoncus, ex eget iaculis convallis, libero mauris sollicitudin mi, quis maximus risus elit ut mauris. Maecenas accumsan ante augue, ut laoreet arcu semper vitae. Nulla convallis dapibus finibus. Sed elementum pulvinar ex sed fermentum. Nullam at erat id ex bibendum fermentum quis ac massa. In rhoncus purus ut est ultrices ultricies.`,
`Sed magna nibh, dapibus sit amet vestibulum tincidunt, tincidunt a justo. Duis venenatis interdum ex sit amet rutrum. Proin tempus vitae lectus nec rutrum. Aliquam imperdiet nisl sed rutrum tempor. Praesent quis fringilla nisi. Etiam sed mi sit amet mi imperdiet placerat nec quis purus. Suspendisse porta magna eget arcu feugiat, ac vestibulum neque gravida. Quisque eu ex id risus tempor interdum.`]

document.addEventListener("DOMContentLoaded", init, false);

function init() {
    form = document.querySelector("form");
    amount = document.querySelector("#amount");
    form.addEventListener("submit", generate, false);
}

function generate() {
    event.preventDefault();
    result = document.querySelector("article");
    let value = Number(amount.value);
    // If the number entered is less than 0, greater than 12 (the amount of paragraphs stored) or equal to 0, return 1 paragraph
    if (value < 0 || value > 12 || value === 0) {
        result.innerHTML = `<p class="text">${loremParagraphs[0]}</p>`;
    }
    // Else return the amount of paragraphs the user entered
    else {
        let tempText = loremParagraphs.slice(0, value);
        tempText = tempText.map(function(item) {
            return `<p class="text">${item}</p>`;
        }).join("<br>");
        result.innerHTML = tempText;
    }
}